### ISSUE TITLE
Use of OSI Keyhole Logo on Twitter

### ISSUE THREAD

**Issue by massonpj** [fossjobs/fossjobs#12]
Hi,

I'm Patrick Masson, GM at the Open Source Initiative. We recently discovered that the fossjobs Twitter account is using the OSI's Keyhole Logo as it's avatar. I'm afraid we need to ask you to please remove the logo. It is a registered trademark, and its use might confuse some folks, implying that fossjobs and the OSI are somehow related.

Please know we very much support your work here and think a job board dedicated to free and open source software is a great contribution to the FOSS movement. We just need to be sure that we keep control of our branding as the OSI logo serves as a certification mark for licenses that have gone through the OSI's license review and approval process.

I always feel like a jerk sending these notices out, so in order to provide a "patch" not just report the bug, I've attached a couple of ideas for a fossjobs.net logo. I noticed the fossjobs.net site does not have a logo, so maybe this could help there too. If you like them, I am happy to assign the copyright to you (I did not use the CC0 or another CC license so that you could control the logo's use, should you decide to go with them).

Thanks for your understanding and please let me know if you have any questions, or if I can help (also happy to keep iterating through logo designs for you).

Take care,
Patrick

![fossjobs01](https://cloud.githubusercontent.com/assets/5924352/24059934/57a6382c-0b27-11e7-9513-7e1b8f9b1b99.png)
![fossjobs02 pnf](https://cloud.githubusercontent.com/assets/5924352/24059935/5a00f940-0b27-11e7-8936-ec49953e265c.png)

**Comment by moba** [comment]
Oh wow. Thanks so much! This is great. For now, I replaced the Twitter profile picture. Of course I welcome pull requests for the website to add the logo(s) there as well, or more logos that we can pick from.

**Comment by massonpj** [comment]
@moba The two links below are to editable files for the two logos I sent over (they were developed in Inkscape). They also include the specifications on fonts and licensing information for the magnifying glass. Most importantly, they include a my signed transfer of copyright you FOSSJobs.net. They're yours now!

https://osi.xwiki.com/bin/download/XWiki/pmasson/FOSSJobs.net.svg
https://osi.xwiki.com/bin/download/XWiki/pmasson/FOSSJobs.net.eps

Good luck,
Patrick

**Comment by elioqoshi** [comment]
I'd be happy to help with an alternative logo as well in case you are looking for one.

**Comment by moba** [comment]
Thanks @elioqoshi, much appreciated! I actually like @massonpj's proposed design, and I don't think we need anything else for now.

What you could help with a small thing. Literally. :) I have not tried it yet, but I'm not so sure the design above works as favicon. Maybe just a magnifying glass with an F inside? Or something else completely? At the moment, I'm using the "jobberbase" original favicon, which is kind-of OK but not really nice.
