### ISSUE TITLE
Captcha for submissions does not actually do work

### ISSUE THREAD

**Issue by moba** [fossjobs/fossjobs#13]
Users don't notice, but we've been getting flooded by spam submissions for quite some time now. The captcha is still displayed, it is just not properly validated. Probably something changed on the reCAPTCHA end, which may or may not be easy to fix. 

The alternative would be to switch to some custom "captcha", I doubt any spambots will adapt to whatever homegrown thing we use.

**Comment by thunderft** [comment]
Google is now reporting that V1 Captcha will be no longer be supported effective March 1, 2018 and any scripts using version 1 will fail.  

Can someone update the Captcha to allow for the latest version 2 (V2) (which uses the 'I am not a robot' version)

**Comment by moba** [comment]
Adopted a homegrown "captcha".
