### ISSUE TITLE
Sources for FOSS jobs

### ISSUE THREAD

**Issue by moba** [fossjobs/fossjobs#19]
I could use some help with monitoring available jobs. If you want to help, whenever you come across an interesting posting please CC us on Twitter, write an email, or ideally fill out the submission form directly.

There are a number of places that one can monitor, and, while not all jobs there will be useful for fossjobs.net, certainly they can help feed us:

Initial list:
 https://twitter.com/jobsopensource
 https://www.redhat.com/en/jobs/categories/technology
 https://sentry.io/jobs/
 https://linux.org.au/jobs/feed 
 https://www.fsf.org/resources/jobs/RSS/
 https://tbe.taleo.net/NA3/ats/servlet/Rss?org=CANONICAL&cws=1&WebPage=SRCHR&WebVersion=0&_rss_version=2 
 https://linaro.recruiterbox.com/jobfeeds/Linaro

Any other sources we should regularly look at?

**Comment by waldyrious** [comment]
Wikimedia publishes job openings in a dedicated Twitter feed https://twitter.com/wikimediaatwork, and there's also a regularly updated listing here: https://wikimediafoundation.org/wiki/Work_with_us#Wikimedia_Careers

**Comment by pabs3** [comment]
Some more, mainly from employers:

https://lwn.net/op/AuthorGuide.lwn
https://www.collabora.com/careers.html
https://www.igalia.com/nc/about-us/
https://www.credativ.com/about/careers
https://jobs.lever.co/endless
https://www.canonical.com/careers/all-vacancies
https://www.codethink.co.uk/join-us.html
https://bootlin.com/company/careers/
https://careers.mozilla.org/

This could also be listed, since people could start self-employment:

https://www.debian.org/consultants/info

**Comment by pabs3** [comment]
Another one:

https://www.sysmocom.de/jobs/

**Comment by pabs3** [comment]
https://www.torproject.org/about/jobs.html

**Comment by pabs3** [comment]
Another:

https://puri.sm/jobs/

**Comment by pabs3** [comment]
Another: https://www.univention.com/about-us/careers/

**Comment by pabs3** [comment]
https://www.catalyst.net.nz/jobs

**Comment by pabs3** [comment]
https://www.linuxfoundation.org/about/careers/

**Comment by pabs3** [comment]
https://jobs.suse.com/search-jobs

**Comment by moba** [comment]
https://jobs.freenode.net/ "aims to connect those looking to hire with the immense talent that can be found within the wider freenode communities. The service is free to use, but companies that find a successful match via the service are encouraged to make a donation to freenode to support the operations of the freenode network"

**Comment by moba** [comment]
Moved to https://github.com/fossjobs/fossjobs/wiki/job-resources

If you want to contribute, you can either open a new issue or ask to get added to the team. Thanks!

**Comment by pabs3** [comment]
Expanded and moved to here:

https://github.com/fossjobs/fossjobs/wiki/resources

**Comment by waldyrious** [comment]
For future reference, I have confirmed that all the links mentioned in the comments above are now listed [in the wiki page](https://github.com/fossjobs/fossjobs/wiki/resources).
