### ISSUE TITLE
Clarify fields in the post page

### ISSUE THREAD

**Issue by waldyrious** [fossjobs/fossjobs#21]
I just tried to [submit](https://www.fossjobs.net/post/) a job opening that was posted elsewhere, and a few things were unclear in that process:

- The textile cheatsheet didn't mention how to markup section headings. I used bold to that effect, but I'm not sure if that's the intention (it certainly isn't the proper semantic markup). I think it would be reasonable to add this extra entry to the cheatsheet.
- The website field was ambiguous as to whether it related to the company's web site (home page), or the page for the specific job posting. A simple change in the placeholder text would make this clear.
- The email field didn't make it clear whether this had to be the contact email for the posting, or the email of the person submitting the job opening (e.g. for spam control). I suppose it could make sense to either have these two as separate fields, or at least clarify that the email is going to be used for both purposes.

I'm willing to submit a PR implementing the proposed fixes above (or whatever variation is deemed appropriate).

**Comment by moba** [comment]
This all sounds like very reasonable suggestions, and I would welcome a pull request! (So far I've used the "website" link to point to the job posting, which makes the most sense to me; it would also be good to include that link again at the bottom of each post in the template)

**Comment by waldyrious** [comment]
What would be your preferred resolution for the third point?

**Comment by moba** [comment]
I don't think anyone is really going to use the "submit your job application by our web form" method. We could rip out that "feature" (a hack would be to simply hide the option and set the default to disabled), and turn the email option unambiguously into the one of the submitter instead of the potential contact email for the job.

**Comment by waldyrious** [comment]
Ok, sounds good to me. I'll try to take a stab at this when I get the time.

**Comment by moba** [comment]
I changed some of the hints now to hopefully make it more clear (email address, URL). About the textile help: I am using "bold" markers myself, I don't know if Jobberbase secretly supports other, more semantically correct markup.

**Comment by waldyrious** [comment]
Thanks for addressing this! Sorry I never got around to do it. For future reference, here are the relevant commits:

> it would also be good to include that link again at the bottom of each post in the template)

Done in d9facbfe5

> I don't think anyone is really going to use the "submit your job application by our web form" method. We could rip out that "feature" (a hack would be to simply hide the option and set the default to disabled)

Done in 389ff33a9

> I changed some of the hints now to hopefully make it more clear (email address, URL).

Done in 6c858629e
