### ISSUE TITLE
Captcha Version 1 no longer supported

### ISSUE THREAD

**Issue by thunderft** [fossjobs/fossjobs#22]
Google is now reporting that V1 Captcha will be no longer be supported effective March 1, 2018 and any scripts using version 1 will fail.  

Can someone update the Captcha to allow for the latest version 2 (V2) (which uses the 'I am not a robot' version)

**Comment by moba** [comment]
OK this will indeed become a problem. I am not sure I will find the time to fix this in time. It's been a while since I've last touched PHP...

**Comment by moba** [comment]
I ripped out the recaptcha code and replaced it by a very simple static check. Let's see how bots deal with this now...
