### ISSUE TITLE
 Install files are corrupt due to being saved as BINARY not ASCII

### ISSUE THREAD

**Issue by thunderft** [fossjobs/fossjobs#23]
It appears that several of the site **_install files_** were supposed to be saved as ASCII files (like the PHP files) **_but were saved as BINARY files in error_**. This is related  to the install packages ready for download from http://www.jobberbase.com and the auto-install package from Softaculous servers. 

I have verified at least 20 different files so far, and still counting.. 

After my install, I have had to FTP files from my shared hosting server over my computer, as a BINARY file so I could copy-n-paste the contents into a new text file saved as ASCII, and then re-upload as ASCII to my server.  **_Re-saving files as ASCII has corrected numerous errors being reported from the server._** 

This is going to be brutal to find all the ASCII files that were accidentally saved as BINARY. 

(Darn that invisible \r  verses  \n)     (That'll get you every time!) 

Is it possible for a developer to re-save the install package with files saved in their correct format? (php files as ASCII, pics as BINARY, etc)

This will most likely solve a lot of issues for people who love Jobberbase.  

Unknown if when that's done a newer version number should be used to differentiate between install  packages with bad Binary files, and a repaired install package.  Maybe  V2.1 ?

Thank you all for the wonderful work you do :)

**Comment by moba** [comment]
Can you please repost that in the Jobberbase repository? This is "just a copy" that we use for fossjobs.net, not Jobberbase itself -- which I think is still located at https://github.com/filipcte/jobberbase/.

Thanks!
