### ISSUE TITLE
Use ISO 8601 format for dates

### ISSUE THREAD

**Issue by waldyrious** [fossjobs/fossjobs#40]
Currently dates are formatted in the `%d.%m.%Y` format (e.g. 09.04.2021), but it as an international project, it would be better if we used a more well-known format — specifically, [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). This would mean switching to the `%Y-%m-%d` format (e.g. 2021-04-09).

I actually tried to dig into the code to find where this change could be made, but got a little lost. I suppose some or all these lines might be relevant:

https://github.com/fossjobs/fossjobs/blob/afc8d8d0288d6113b1d1c274b4f12bc408d90912/public/_templates/bulma/home.tpl#L36

https://github.com/fossjobs/fossjobs/blob/afc8d8d0288d6113b1d1c274b4f12bc408d90912/public/_includes/class.Job.php#L52

https://github.com/fossjobs/fossjobs/blob/afc8d8d0288d6113b1d1c274b4f12bc408d90912/public/_config/config.settings.php#L23

https://github.com/fossjobs/fossjobs/blob/afc8d8d0288d6113b1d1c274b4f12bc408d90912/public/_includes/smarty/libs/plugins/modifier.date_format.php#L31

https://github.com/fossjobs/fossjobs/blob/afc8d8d0288d6113b1d1c274b4f12bc408d90912/db/jobberbase.sql#L531

...but I seem to have reached a dead-end, since none of these specify the DD.MM.YYYY format. Any hints at to where this change would be made?

**Comment by moba** [comment]
I suspect it is a system setting? Will have a closer look.

**Comment by moba** [comment]
`$settings['date_format']` is a configuration option in the admin backend. I changed it to `%Y-%m-%d` now on the live site. Thanks!
