### ISSUE TITLE
Could you add a bot to Mastodon?

### ISSUE THREAD

**Issue by qbi** [fossjobs/fossjobs#64]
Since some time many people, esp. from the area of Open Source / Free Software, moved to Mastodon. Could you add a bot to Mastodon which posts the jobs there

**Comment by midzer** [comment]
There is @fossjobs@fosstodon.org

**Comment by qbi** [comment]
Argl, I should strengthen my search skills … 
Sorry for the noise.

**Comment by waldyrious** [comment]
Sorry for the off-topic, but does anyone know of an Android app for Mastodon that allows subscribing to an account to receive push notifications whenever the account posts? I had this feature active for the [fossjobs_net](https://twitter.com/fossjobs_net) account on Twitter, and I'm missing it on Mastodon.

**Comment by midzer** [comment]
@waldyrious In the offical WebApp there is a "bell" button in each user profile to subscribe to push notifications (I have not tested it though)

**Comment by waldyrious** [comment]
Thanks for the tip, but I was really looking for something that would work on mobile. Unfortunately I haven't found a solution for that yet. 😔

**Comment by midzer** [comment]
The WebApp doesnt work on mobile properly?

**Comment by waldyrious** [comment]
It doesn't seem like it. I have opened the web app in a mobile browser and granted it permission to send notifications, but it's been a couple days and I haven't gotten any notifications.

**Comment by midzer** [comment]
Hmm, reads like a bug in the Mastodon WebApp?

**Comment by waldyrious** [comment]
Sure — anyway, let's leave it at that for this thread because it's far off-opic already! :sweat_smile:
