### ISSUE TITLE
www.fossjobs.net is inaccessible

### ISSUE THREAD

**Issue by faithuniterh** [fossjobs/fossjobs#65]
At this particular time, the website to fossjobs.net is inaccessible. It has been this way for the past week as of the time of writing.

Below is the output of the curl response

`
curl -Is https://www.fossjobs.net/ 
`

`
HTTP/1.0 500 Internal Server Error
Date: Thu, 24 Aug 2023 09:56:07 GMT
Server: Apache
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Connection: close
Content-Type: text/html; charset=UTF-8
`

Since this is a community project, how can we assist?

**Comment by moba** [comment]
Whoops! Back up now. Will revise the checks that are supposed to notify when it goes away...
