### ISSUE TITLE
worldwide jobs -> only display [full-time] does not work

### ISSUE THREAD

**Issue by moba** [fossjobs/fossjobs#9]
Example: Web site error:

Origin: http://www.fossjobs.net/jobs-worldwide/
Destiny: http://www.fossjobs.net/jobs-in//fulltime/

The error is: http://www.fossjobs.net/page-unavailable/

**Comment by bblough** [comment]
Target link should be http://www.fossjobs.net/jobs-worldwide/fulltime

Same issue applies to parttime, freelance, and internship links as well.
